/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Vela - Docs",
  "tagline": "Documentation",
  "url": "https://docs-vela.botlhale.xyz",
  "baseUrl": "/",
  "onBrokenLinks": "warn",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "Botlhale-AI",
  "projectName": "docs-vela",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "presets": [
    [
      "@docusaurus/preset-classic",
      {
        "docs": {
          "routeBasePath": "/",
          "sidebarPath": "/Users/athi/Desktop/docs-coaching-portal/sidebars.js",
          "showLastUpdateTime": true,
          "showLastUpdateAuthor": true
        },
        "blog": false,
        "theme": {
          "customCss": [
            "/Users/athi/Desktop/docs-coaching-portal/src/css/custom.css",
            "/Users/athi/Desktop/docs-coaching-portal/src/css/navigation.css"
          ]
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/logo.png",
    "navbar": {
      "title": "Vela Coaching Portal",
      "logo": {
        "alt": "Vela Logo",
        "src": "img/logo.png",
        "srcDark": "img/logo.png"
      },
      "items": [
        {
          "type": "html",
          "position": "right",
          "value": "<a href=\"https://vela.botlhale.xyz/register\" target=\"_blank\" class=\"auth-button auth-button-signup\">Create Account</a>"
        },
        {
          "type": "html",
          "position": "right",
          "value": "<a href=\"https://vela.botlhale.xyz/login\" target=\"_blank\" class=\"auth-button auth-button-signin\">Log In</a>"
        },
        {
          "href": "https://github.com/botlhale-ai",
          "position": "right",
          "className": "header-github-link",
          "aria-label": "GitHub repository"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "light",
      "links": [
        {
          "title": "Documentation",
          "items": [
            {
              "label": "Dashboard",
              "to": "/docs/Dashboard"
            },
            {
              "label": "Calls",
              "to": "/docs/Calls"
            },
            {
              "label": "Agents",
              "to": "/docs/Agents"
            }
          ]
        },
        {
          "title": "Features",
          "items": [
            {
              "label": "Smart Detector",
              "to": "/docs/Smart Detector"
            },
            {
              "label": "Reports",
              "to": "/docs/Reports"
            },
            {
              "label": "Settings",
              "to": "/docs/Settings"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Release Notes",
              "to": "/docs/release-notes"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/botlhale-ai"
            },
            {
              "label": "Contact Support",
              "href": "mailto:support@botlhale.ai"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Botlhale AI. All rights reserved."
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "head": [
      {
        "tagName": "link",
        "attributes": {
          "rel": "stylesheet",
          "href": "https://fonts.googleapis.com/css?family=Open+Sans:400,700&display=swap"
        }
      },
      {
        "tagName": "link",
        "attributes": {
          "rel": "stylesheet",
          "href": "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
        }
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "scripts": [
    {
      "src": "/js/themeToggle.js",
      "async": true
    },
    {
      "src": "https://kit.fontawesome.com/3d32eadabe.js",
      "crossorigin": "anonymous"
    }
  ],
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
